### PR TITLE
copied files from solution repo

### PR DESCRIPTION
**Pull request by mrbenbot**
see https://github.com/CodeYourFuture/JavaScript-Core-2-Coursework-Week3-Solution/pull/4

### CODE REVIEW

**Review by illicitonion — APPROVED** [review]
This is really nice, thanks!

One thing I'm wondering, reading it - in real life I'd probably also want to have have some non-JSDOM unit tests for a function called `formatSeconds` or similar (maybe instead of "should split values over 60 seconds...", maybe as well as) - along the lines of:

```js
describe("formatSeconds", () => {
  test("single digit seconds" => { expect(formatSeconds("5").toBe("00:05"); });
  test("minutes and seconds" => { expect(formatSeconds("75").toBe("01:15"); });
  ...
});
```

This would impose some structure on the trainees code, but that may be a good thing... But teaching them the concept of unit tests as smaller seems useful... Any thoughts on how to go about something like this? /cc @CodeYourFuture/syllabus-team

**Comment by alismith-dev** [comment]
> some non-JSDOM unit tests for a function called formatSeconds

I like this idea, however I don't think they can be entirely outside the context of JSDOM, otherwise we'd have to export that function. And I don't think explaining that is worth the tradeoff, having "unit" tests mixed in with "integration" tests is fine to me.

> But teaching them the concept of unit tests as smaller seems useful... 

I feel like this is a bit early to worry about different styles of test: we can cover this more explicitly in the proposed "theory of tests" lesson.

**Comment by alismith-dev** [comment]
Also thanks @mrbenbot for taking this!!

**Comment by alismith-dev** [comment]
>  I don't think they can be entirely outside the context of JSDOM, otherwise we'd have to export that function

Ah, for some reason I had thought that the scope of the JSDOM page was accessible in the test, but I've just learned that this isn't the case.

That's unfortunate, especially as we'd have to use CJS not ESM which I would imagine would just lead to confusion when we introduce it. Tbh, this is making me doubt the whole testing strategy a bit.

Apologies for the continual edits: ~I think I forgot that we already are relying on module systems in our other tests. So this is probably fine actually.~ Gah, no I had it right the first time - in our JS1 tests, they are just appended to the bottom of the file, so no module system needed.

**Pull request merged**
